CREATE TABLE invoices (
  id                                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sequence_id                           TEXT NOT NULL,

  order_id                              UUID NOT NULL REFERENCES exhibit_orders(id) ON DELETE CASCADE,
  user_id                               UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  invoice_title                         TEXT NOT NULL,
  tax_no                                TEXT NOT NULL DEFAULT '',
  email                                 TEXT NOT NULL,

  request                               JSONB NOT NULL,
  response                              JSONB NOT NULL,
  status                                TEXT NOT NULL,
  invoice_no                            TEXT,
  created_at                            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT chk_invoice_applications_status
    CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),
  CONSTRAINT uq_invoice_applications_sequence_id UNIQUE (sequence_id)
);

CREATE INDEX idx_invoice_applications_user_id_created_at
  ON invoices(user_id, created_at DESC);

CREATE INDEX idx_invoice_applications_order_id
  ON invoices(order_id);