include /var/lib/cr7/etc/nginx/snippets/api.conf;
include /var/lib/cr7/etc/nginx/snippets/wechat.conf;
include /var/lib/cr7/etc/nginx/snippets/data.conf;

access_log /var/log/nginx/cr7/access.log;
error_log  /var/log/nginx/cr7/error.log warn;

client_max_body_size 1000M;
send_timeout 20m;
proxy_read_timeout 20m;

root /var/lib/cr7/home/;
location / {
  try_files $uri $uri/ /index.html;
}