ignoreWords:
  - amiceli
  - errcode
  - errmsg
  - Jscode
  - Descriibe
  - wechatpay
  - ciphertext
  - JSAPI
  - NOTPAY

words:
  - apiclient
  - Luhn
  - mchid
  - moleculer
  - TSTZRANGE
  - wechat
  - Wechat
