ignoreWords:
  - amiceli
  - errcode
  - errmsg
  - Jscode
  - Descriibe
  - wechatpay
  - ciphertext
  - JSAPI
  - NOTPAY
  - skus
words:
  - apiclient
  - cdkey
  - cdkeys
  - Ctrip
  - Damai
  - eticket
  - fapiao
  - inventorys
  - Luhn
  - mchid
  - moleculer
  - qrcode
  - TSTZRANGE
  - wechat
  - Wechat
  - xiecheng
